# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # DevStack node
  config.vm.define "devstack" do |devstack|
    devstack.vm.box = "ubuntu/bionic64"
    devstack.vm.network "private_network", ip: "192.168.33.104"
    devstack.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 2
    end
  end
end