{% if inventory_hostname.startswith('mgmt') %}
  {% set addr = 200 %}
{% elif inventory_hostname.startswith('stor') %}
  {% set addr = 100 %}
{% else %}
  {% set addr = 0 %}
{% endif %}
{% if inventory_hostname.endswith('01') %}
  {% set addr = addr + 1 %}
{% elif inventory_hostname.endswith('02') %}
  {% set addr = addr + 2 %}
{% else %}
  {% set addr = addr + 3 %}
{% endif %}
# {{ ansible_managed }}
network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
    geth0:
      dhcp4: false
{% if not inventory_hostname.startswith('stor') %}
    geth1:
      dhcp4: false
    geth2:
      dhcp4: false
{% endif %}
    tgeth0:
      dhcp4: false
{% if inventory_hostname.startswith('stor') %}
    tgeth1:
      dhcp4: false
      addresses: [ '10.0.8.{{ addr }}/24' ]
{% endif %}
  bridges:
    br-mgmt:
      interfaces: [ geth0 ]
      addresses: [ '10.0.10.{{ addr }}/24' ]
    br-storage:
      interfaces: [ tgeth0 ]
      addresses: [ '10.0.9.{{ addr }}/24' ]
{% if not inventory_hostname.startswith('stor') %}
    br-vxlan:
      interfaces: [ geth1 ]
      addresses: [ '10.0.30.{{ addr }}/24' ]
{% endif %}
    br-vlan:
      interfaces: [ geth2 ]
