---
- hosts: all
  become: yes
  tasks:
    - name: Configure udev rules
      template:
        src: ./udev.rules
        dest: /etc/udev/rules.d/70-persistent-net.rules
      notify:
        - Apply udev changes

    - name: Disable cloud init network config
      copy:
        src: ./cloud-init.yml
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

    - name: Configure netplan
      template:
        src: ./netplan.yml
        dest: /etc/netplan/50-cloud-init.yaml
      notify:
        - Apply netplan changes

  handlers:
    - name: Apply netplan changes
      command: netplan apply
    
    - name: Apply udev changes
      shell: udevadm control --reload-rules && udevadm trigger
