# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.ssh.insert_key = "false"

  # Management nodes
  config.vm.define "mgmt01" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027000001"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "08002700FF01"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
  config.vm.define "mgmt02" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027000002"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "08002700FF02"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
  config.vm.define "mgmt03" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027000003"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "08002700FF03"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Storage nodes
  config.vm.define "stor01" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027AA0001"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027AAFF01"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage_backend", mac: "080027AABB01"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
  config.vm.define "stor02" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027AA0002"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027AAFF02"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage_backend", mac: "080027AABB02"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
  config.vm.define "stor03" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027AA0003"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027AAFF03"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage_backend", mac: "080027AABB03"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Compute nodes
  config.vm.define "nova01" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027BB0001"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027BBFF01"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
    end
  end
  # Compute nodes
  config.vm.define "nova02" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027BB0002"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027BBFF02"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
    end
  end
  # Compute nodes
  config.vm.define "nova03" do |config|
    config.vm.box = "ubuntu/bionic64"
    # Configure NICs
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "management", mac: "080027BB0003"
    config.vm.network "private_network", auto_config: false,
      virtualbox__intnet: "storage", mac: "080027BBFF03"
    
    # Configure Resourcees
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 6144
      vb.cpus = 4
    end
  end
end